server:
  port: 33088
spring:
  main:
    banner-mode: off
  datasource:
    url: ENC(Qyli4hKrqFUV1lnl7868PXnRc54W7f53MlqgLJR2DrFJNf6GBdvkPQfdHl6tpeQ89eEVpO1uif9SGDFK5lig4TeyaXT8FPMeYXO+nNj3x7xKK8SAgaut+iVsnoPBhz1ARGMC3OwgaJRA0ADKYLoHuXTDbV36KINUnwq3/x63z9kd25JNhD/h4qCa7kI0s7Qpb376gIHO38QMI7JM8b6lFEE4Bt95pzKepwiGSXwQ7+wzjGtx6/XrGYRh9Hfeqb3cqxfMGAi1GeZ/vdKgS1cVG7TjhXuUkP2n6fRpPrFIGSb3jwIeO/OcfCAc/ORiD6fp)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(hsbT3itK+X/yMGB9Gt/xcg==)
    password: ENC(K7EE3efZSpVfMOMN0eKpjVmkW6Ogx286)
  threads:
    virtual:
      enabled: true
logging:
  config:
    loggers:
      com.baomidou.mybatisplus.core: DEBUG
  level:
    com.itheima: debug
  pattern:
    dateformat: HH:mm:ss
#mybatis:
#  mapper-locations: classpath*:mapper/*.xml #mapper.xml ????????
#  configuration:
#    map-underscore-to-camel-case: true # ???????????
#    cache-enabled: false # ????????

# mybatis-plus配置文件
mybatis-plus:
  # 拦截器配置
  interceptor:
    - com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor
  # 配置项
  configuration:
    map-underscore-to-camel-case: true # 将下划线转为驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 日志实现类
    cache-enabled: false # 是否启用缓存
  # 全局配置
  global-config:
    banner: false # 是否显示banner
    db-config:
      id-type: ASSIGN_ID # 自动生成主键类型
      update-strategy: not_null # 更新策略
  # mapper配置
  mapper-locations: classpath*:mapper/**/*.xml # mapper.xml文件路径
  type-aliases-package: com.itheima.mp.domain.po # 类型别名包路径
  # type-aliases-super-type: # 类型别名超类路径

yirc99:
  WxSecret: ENC(sjHa4toKczeyage0OZzdm2QFwk47NUC0amAZMkiNLoqagejveDORfSIO58PfpGAo)
  filePath: /src/main/resources/static/avatar/
  feedbackImgPath: /src/main/resources/static/feedback/
  Template:
    id: R0HVPNJRywpmvaA5xO6YWFfjLdGqcjWPB0-rqRkmkbk
