server:
  port: 33088
spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mygoschool?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: yirc99
    password: zhu020929
  threads:
    virtual:
      enabled: true
logging:
  config:
    loggers:
      com.baomidou.mybatisplus.core: DEBUG
  level:
    com.itheima: debug
  pattern:
    dateformat: HH:mm:ss
#mybatis:
#  mapper-locations: classpath*:mapper/*.xml #mapper.xml ????????
#  configuration:
#    map-underscore-to-camel-case: true # ???????????
#    cache-enabled: false # ????????

# mybatis-plus配置文件
mybatis-plus:
  # 拦截器配置
  interceptor:
    - com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor
  # 配置项
  configuration:
    map-underscore-to-camel-case: true # 将下划线转为驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 日志实现类
    cache-enabled: false # 是否启用缓存
  # 全局配置
  global-config:
    banner: false # 是否显示banner
    db-config:
      id-type: assign_uuid # 自动生成主键类型
      update-strategy: not_null # 更新策略
  # mapper配置
  mapper-locations: classpath*:mapper/**/*.xml # mapper.xml文件路径
  type-aliases-package: com.itheima.mp.domain.po # 类型别名包路径
  # type-aliases-super-type: # 类型别名超类路径


yirc99:
  WxSecret: b8f93fdabc2c7dfbaea3c626c77438cd
  filePath: /src/main/resources/static/avatar/
